flowchart LR

subgraph internalca[Internal CA Compute]
    %% internalop[Operator]
    internalcert[Consumer Cert]
    internalsecret[Consumer Secret]
end
%% internalop --> internalCertExport
internalcert <--> consumerCertInt
internalsecret <--> consumerSecretInt

subgraph externalca[External CA Compute]
    %% externalop[Operator]
    externalcert[Consumer Cert]
    externalsecret[Consumer Secret]
end
%% externalop --> externalCertExport
externalcert <--> consumerCertExt
externalsecret <--> consumerSecretExt


subgraph kcp

    %% subgraph internalws[Internal CA Workspace]
    %%     internalCertExport[Internal CA APIExport]
    %% end
    %% internalCertExport --> internalvw

    %% subgraph externalws[External CA Workspace]
    %%     externalCertExport[External CA APIExport]
    %% end
    %% externalCertExport --> externalvw

    subgraph platform[Platform Workspace]
        subgraph internalvw[Internal CA VW]
            consumerCertInt[Consumer Cert]
            consumerSecretInt[Consumer Secret]
        end

        subgraph externalvw[External CA VW]
            consumerCertExt[Consumer Cert]
            consumerSecretExt[Consumer Secret]
        end
    end

    subgraph consumer[Consumer Workspace]
        subgraph consumervw[Consumer VW]
            consumerCertVW[Consumer Cert]
            consumerSecretVW[Consumer Secret]
        end
        consumerCertInt <--> consumerCertVW
        consumerSecretInt <--> consumerSecretVW
        consumerCertExt <--> consumerCertVW
        consumerSecretExt <--> consumerSecretVW

        consumerCert[Consumer Cert]
        consumerCertVW <--> consumerCert
        consumerSecret[Consumer Secret]
        consumerSecretVW <--> consumerSecret
    end

end
