apiVersion: operator.kcp.io/v1alpha1
kind: RootShard
metadata:
  name: root
spec:
  image:
    # There's a bug that the IP of the pod and the default 6443 port is
    # used as the VW base url. This doesn't work with kcp running in
    # a kube cluster, which uses :6443 itself. This is fixed in main but
    # not in the release version kcp-operator deploys.
    tag: 8dae1f51e
  # Setting the shardBaseURL here only works because this is
  # a single-shard setup. In multi-shard setups, each shard would
  # need to have its own correct URL and be exposed through an ingress.
  # shardBaseURL: https://broker-platform-control-plane:443/rootshard
  external:
    hostname: broker-platform-control-plane
    port: 443
  certificates:
    issuerRef:
      group: cert-manager.io
      kind: Issuer
      name: selfsigned
  cache:
    embedded:
      enabled: true
  etcd:
    endpoints:
      - http://kcp-etcd-client.default.svc.cluster.local:2379
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: kcp-root
#   annotations:
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   tls:
#     - hosts:
#         - broker-platform-control-plane
#       secretName: root-server
#   rules:
#     - host: broker-platform-control-plane
#       http:
#         paths:
#           - path: /rootshard/(.*)
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: root-kcp
#                 port:
#                   number: 6443
---
apiVersion: operator.kcp.io/v1alpha1
kind: FrontProxy
metadata:
  name: frontproxy
spec:
  rootShard:
    ref:
      name: root
  certificateTemplates:
    server:
      spec:
        dnsNames:
          - localhost
        ipAddresses:
          - 127.0.0.1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kcp-proxy
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - hosts:
        - broker-platform-control-plane
      secretName: root-frontproxy-server
  rules:
    - host: broker-platform-control-plane
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontproxy-front-proxy
                port:
                  number: 6443
---
apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: kubeconfig-kcp-admin
spec:
  username: kcp-admin
  groups:
    - system:kcp:admin
  validity: 8766h
  secretRef:
    name: admin-kubeconfig
  target:
    frontProxyRef:
      name: frontproxy
---
apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: kubeconfig-kcp-operator
spec:
  username: kcp-admin
  groups:
    - system:kcp:admin
  validity: 8766h
  secretRef:
    name: operator-kubeconfig
  target:
    rootShardRef:
      name: root
